// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppNote struct {
	ID        int64
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppUser struct {
	ID           int64
	Email        string
	DisplayName  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
