// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlcdb

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO app_notes (
    title,
    body
) VALUES (
    $1,
    $2
)
RETURNING id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	Title string
	Body  string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (AppNote, error) {
	row := q.db.QueryRow(ctx, createNote, arg.Title, arg.Body)
	var i AppNote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, body, created_at, updated_at
FROM app_notes
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListNotes(ctx context.Context) ([]AppNote, error) {
	rows, err := q.db.Query(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppNote
	for rows.Next() {
		var i AppNote
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
