// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*)
FROM app_notes
WHERE user_id = $1
  AND CASE
    WHEN $2::text IS NULL OR $2::text = '' THEN TRUE
    ELSE title ILIKE '%' || $2::text || '%'
END
`

type CountNotesParams struct {
	UserID    pgtype.Int8
	QueryText pgtype.Text
}

func (q *Queries) CountNotes(ctx context.Context, arg CountNotesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotes, arg.UserID, arg.QueryText)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO app_notes (
    user_id,
    title,
    body
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	UserID pgtype.Int8
	Title  string
	Body   string
}

type CreateNoteRow struct {
	ID        int64
	UserID    pgtype.Int8
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (CreateNoteRow, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.Title, arg.Body)
	var i CreateNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM app_notes
WHERE id = $1
  AND user_id = $2
`

type DeleteNoteParams struct {
	ID     int64
	UserID pgtype.Int8
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, title, body, created_at, updated_at
FROM app_notes
WHERE id = $1
  AND user_id = $2
`

type GetNoteByIDParams struct {
	ID     int64
	UserID pgtype.Int8
}

type GetNoteByIDRow struct {
	ID        int64
	UserID    pgtype.Int8
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (GetNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.UserID)
	var i GetNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, user_id, title, body, created_at, updated_at
FROM app_notes
WHERE user_id = $1
  AND CASE
    WHEN $2::text IS NULL OR $2::text = '' THEN TRUE
    ELSE title ILIKE '%' || $2::text || '%'
END
ORDER BY
    CASE WHEN $3::text = 'title' AND $4::text = 'asc' THEN title END ASC,
    CASE WHEN $3::text = 'title' AND $4::text = 'desc' THEN title END DESC,
    CASE WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN created_at END ASC,
    CASE WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN created_at END DESC,
    id DESC
LIMIT $6
OFFSET $5
`

type ListNotesParams struct {
	UserID        pgtype.Int8
	QueryText     pgtype.Text
	SortField     string
	SortDirection string
	OffsetCount   int32
	LimitCount    int32
}

type ListNotesRow struct {
	ID        int64
	UserID    pgtype.Int8
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes,
		arg.UserID,
		arg.QueryText,
		arg.SortField,
		arg.SortDirection,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesRow
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE app_notes
SET title = $2,
    body = $3,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $4
RETURNING id, user_id, title, body, created_at, updated_at
`

type UpdateNoteParams struct {
	ID     int64
	Title  string
	Body   string
	UserID pgtype.Int8
}

type UpdateNoteRow struct {
	ID        int64
	UserID    pgtype.Int8
	Title     string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (UpdateNoteRow, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.UserID,
	)
	var i UpdateNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
