// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*)
FROM app_notes
WHERE CASE
    WHEN $1::text IS NULL OR $1::text = '' THEN TRUE
    ELSE title ILIKE '%' || $1::text || '%'
END
`

func (q *Queries) CountNotes(ctx context.Context, queryText pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countNotes, queryText)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO app_notes (
    title,
    body
) VALUES (
    $1,
    $2
)
RETURNING id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	Title string
	Body  string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (AppNote, error) {
	row := q.db.QueryRow(ctx, createNote, arg.Title, arg.Body)
	var i AppNote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM app_notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, title, body, created_at, updated_at
FROM app_notes
WHERE id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id int64) (AppNote, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i AppNote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, body, created_at, updated_at
FROM app_notes
WHERE CASE
    WHEN $1::text IS NULL OR $1::text = '' THEN TRUE
    ELSE title ILIKE '%' || $1::text || '%'
END
ORDER BY
    CASE WHEN $2::text = 'title' AND $3::text = 'asc' THEN title END ASC,
    CASE WHEN $2::text = 'title' AND $3::text = 'desc' THEN title END DESC,
    CASE WHEN $2::text = 'created_at' AND $3::text = 'asc' THEN created_at END ASC,
    CASE WHEN $2::text = 'created_at' AND $3::text = 'desc' THEN created_at END DESC,
    id DESC
LIMIT $5
OFFSET $4
`

type ListNotesParams struct {
	QueryText     pgtype.Text
	SortField     string
	SortDirection string
	OffsetCount   int32
	LimitCount    int32
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]AppNote, error) {
	rows, err := q.db.Query(ctx, listNotes,
		arg.QueryText,
		arg.SortField,
		arg.SortDirection,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppNote
	for rows.Next() {
		var i AppNote
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE app_notes
SET title = $2,
    body = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, body, created_at, updated_at
`

type UpdateNoteParams struct {
	ID    int64
	Title string
	Body  string
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (AppNote, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.ID, arg.Title, arg.Body)
	var i AppNote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
