// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO app_refresh_tokens (
    user_id,
    token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AppRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i AppRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveRefreshToken = `-- name: GetActiveRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at
FROM app_refresh_tokens
WHERE user_id = $1
  AND token_hash = $2
  AND revoked_at IS NULL
  AND expires_at > $3
`

type GetActiveRefreshTokenParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetActiveRefreshToken(ctx context.Context, arg GetActiveRefreshTokenParams) (AppRefreshToken, error) {
	row := q.db.QueryRow(ctx, getActiveRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i AppRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE app_refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokensByUser = `-- name: RevokeRefreshTokensByUser :execrows
UPDATE app_refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensByUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
